### PR TITLE
Docs - Create landing page for legacy docs redirection

### PR DESCRIPTION
**Pull request by lucas-tortora**
# Description of change

As we aim to permanently redirect all the [legacy docs](https://legacy.docs.iota.org/) to the Wiki, we wanted to provide a landing page explaining the redirection to our users, as well as giving them basic orientation in the wiki.  To do so, we've created a page with a brief statement about the redirection, and the cards from the Wiki's home page.  

We''ve created the CardWithImage component from the Card function in the home page to be able to reuse it.  

- Created CardWithImage component from Card function to be able to reuse it legacy.mdx
- Created legacy docs redirection landing page. 
- Added legacy.mdx to build sidebars.js

## Links to any relevant issues

https://github.com/iotaledger/devops/issues/311

## Type of change

- Enhancement (a non-breaking change which adds functionality)
- Documentation Enhancement

## How the change has been tested

Wiki was built locally.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have tested the wiki locally and tested that all external links work

## Open Questions

* Would it be better to use the [build home page](https://wiki.iota.org/build/welcome) cards?

### CODE REVIEW

**Comment by Dr-Electron** [comment]
I would add the legacy docs as independent side under wiki.iota.org/legacy or something like that

**Comment by lucas-tortora** [comment]
> I would add the legacy docs as independent side under wiki.iota.org/legacy or something like that

There is a lot of legacy docs, most of which are no longer valid (and won't be in the foreseeable future).  Other than the amount of time it'd take to migrate all of the to docusarus, they would not add any content that we want our users to find and would make our search results less relevant.  The idea is to get rid of the legacy docs for the most part, but add the relevant content such as the [blue prints](https://github.com/lucas-tortora/blueprints/) to the wiki.  

This landing page is aimed at any user who's clicked a link to the legacy docs, which will redirect to the wiki in the short term (if they don't already).

**Comment by Dr-Electron** [comment]
> > I would add the legacy docs as independent side under wiki.iota.org/legacy or something like that
> 
> There is a lot of legacy docs, most of which are no longer valid (and won't be in the foreseeable future). Other than the amount of time it'd take to migrate all of the to docusarus, they would not add any content that we want our users to find and would make our search results less relevant. The idea is to get rid of the legacy docs for the most part, but add the relevant content such as the [blue prints](https://github.com/lucas-tortora/blueprints/) to the wiki.
> 
> This landing page is aimed at any user who's clicked a link to the legacy docs, which will redirect to the wiki in the short term (if they don't already).

Yeah, sorry my bad. I meant the legacy landing page not the whole legacy website.
Like in [this PR](https://github.com/lucas-tortora/iota-wiki/pull/4)

**Comment by lucas-tortora** [comment]
> > > I would add the legacy docs as independent side under wiki.iota.org/legacy or something like that
> > 
> > 
> > There is a lot of legacy docs, most of which are no longer valid (and won't be in the foreseeable future). Other than the amount of time it'd take to migrate all of the to docusarus, they would not add any content that we want our users to find and would make our search results less relevant. The idea is to get rid of the legacy docs for the most part, but add the relevant content such as the [blue prints](https://github.com/lucas-tortora/blueprints/) to the wiki.
> > This landing page is aimed at any user who's clicked a link to the legacy docs, which will redirect to the wiki in the short term (if they don't already).
> 
> Yeah, sorry my bad. I meant the legacy landing page not the whole legacy website. Like in [this PR](https://github.com/lucas-tortora/iota-wiki/pull/4)

Ohh, yes, that's much better.  Merged :)

**Review by Dr-Electron — APPROVED** [review]

**Review by Critical94 — APPROVED** [review]

**Pull request merged**
