### PR TITLE
Rest of page templates, Seo and full menu structure with category.jsom position files

### PR DESCRIPTION
**Pull request by Phyloiota**
# Description of change

Please write a summary of your changes and why you made them. 

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes issue #`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Documentation Fix
- Documentation Enhancment

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested the wiki locally and tested that all external links work

### CODE REVIEW

**Review by AdamCroply — COMMENTED** [review]
It should always be NFTs all file names should be in lower case no spaces

**Comment by AdamCroply** [comment]
Okies, so the pages seem to look alright, just the one issue I can see with changing the nfts and removing special characters. The sidebars won't be using category.json. Each navbar item will have its own sidebar.js file that will contain all the pages, and we can sort these out with Jeroen and Electron, when they get to it.

**Comment by Phyloiota** [comment]
> Okies, so the pages seem to look alright, just the one issue I can see with changing the nfts and removing special characters. The sidebars won't be using category.json. Each navbar item will have its own sidebar.js file that will contain all the pages, and we can sort these out with Jeroen and Electron, when they get to it.

Cool thank you for that info. With nft special character you mean the ' in the filename? ill remove them... i think have em in a few others also

**Comment by AdamCroply** [comment]
All looks good now

**Review by AdamCroply — APPROVED** [review]

**Pull request merged**
