### PR TITLE
Docs - Add Integration Services

### PR DESCRIPTION
**Pull request by lucas-tortora**
# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes issue #`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Documentation Fix
- Documentation Enhancement

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested the wiki locally and tested that all external links work

### CODE REVIEW

**Review by mastrogiovanni — APPROVED** [review]

**Comment by Dr-Electron** [comment]
I think we already talked about this, but I think I would move this into it's on section beside build. @jlvandenhout and @Critical94 what do you think?

**Comment by jlvandenhout** [comment]
Yes, we discussed this and basically "Integration Services" and the description that goes with it indicate a broader scope than what it actually provides (Streams and DID integration). I like the idea of these kind of integrations, but let's give them their own top level space called "Integrate" or something similar and have this specific project listed as a subsection called "DID and Streams integration" or something, which conveys more clearly what is behind the link. The blueprints provided by Ruben would fit nicely in this "integrate" section as well I think.

**Comment by jlvandenhout** [comment]
The reason for my above point of view is that I'd like the Build section to focus on project specific documentation and examples, listing core and support libraries. Logically these kind of integration examples do not fit in that category per se and they deserve their own area imho.

**Comment by lucas-tortora** [comment]
We did talk about it, but it didn't seem there was any conclusion.  I've got no objections to adding a new section, though integrate and build are a bit too close if you ask me.  Until we've got the new layout, icons, and card, it'd be good if we can add this content somewhere.  The discussion on discord lead me to understand we'd add it to the megamenu in the meantime, as JSTo had said under Chrysalis iI placed it there.

**Comment by jlvandenhout** [comment]
Ok agreed, until we have more content I'm fine putting it in build. But I'd still put it under an "Integrations" header and the link something like "Streams and Identity" for clarity and make room for other integrations. wdyt?

**Comment by lucas-tortora** [comment]
> Ok agreed, until we have more content I'm fine putting it in build. But I'd still put it under an "Integrations" header and the link something like "Streams and Identity" for clarity and make room for other integrations. wdyt?

Sounds good to me :)  .   Where it is now or under Getting Started that there's a bit more room?

**Comment by Dr-Electron** [comment]
I like where it is now with a subhead. But probably putting it under Getting started would fit better 🤔

**Comment by lucas-tortora** [comment]
@jlvandenhout  and @Dr-Electron , please take a look whenever you have a moment.  If it's not quite right we can try different positions in the menu until everyone's happy :)

**Comment by Critical94** [comment]
Can we add this section as well to the [build welcome cards](https://wiki.iota.org/build/networks/iota-1.5)? 
E.g.:

Screenshot_3

**Review by jlvandenhout — APPROVED** [review]
LGTM! We should reflect the position of blueprints under "Integrations" in the "Getting Started" cards in the menu and mega menu as well. So we move the blueprints out of "Getting started" and put them in their own section under "Integrations", next to "Streams and Identity", but I'll create a separate issue and PR for that. We can merge this as it is.

**Pull request merged**
