### PR TITLE
Make socials configurable

### PR DESCRIPTION
**Pull request by jlvandenhout**
This will allow to configure the socials bar from the Docusaurus config file.

### CODE REVIEW

**Comment by Dr-Electron** [comment]
The icon and title seems somehow redundant. That's why I wanted to add a LUT to the Team PR with the mapping of title to icon. Do you think it would be useful if we have a global LUT for that?

**Comment by jlvandenhout** [comment]
I think that's reasonable to do, we could even check the links which social it points to, so the config just contains the links.

**Comment by Dr-Electron** [comment]
> I think that's reasonable to do, we could even check the links which social it points to, so the config just contains the links.

Good point.
Do you want to implement that in this PR or should I merge and we do it with later on?

**Comment by jlvandenhout** [comment]
Let's merge this and have a look at it later as we have to think about a few other things too (how to configure different icon fonts more easily for example, automatically calculate the color gradients and Discord is not easy to autodetect from the url)

**Review by Dr-Electron — APPROVED** [review]

**Pull request merged**
