### PR TITLE
Fix mega menu

### PR DESCRIPTION
**Pull request by jlvandenhout**
# Description of change

I removed some unnecessary swizzled components and I re-implemented the megamenu based on the new dropdown component provided by Docusaurus in beta.18. To make it work, I needed to swizzle the primary menu component of the mobile navbar, so it properly passes the mobile property to the navbar item components.

This is a temporary fix, as we will be able to add custom components properly soon.

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Tested locally and also by adding a versioning dropdown, to make sure that doesn't break.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested the wiki locally and tested that all external links work

### CODE REVIEW

**Comment by Dr-Electron** [comment]
LGTM. Although we should still fix the Safari Layout. Something is off there 😅

**Comment by Dr-Electron** [comment]
To me it looks like the arrow component defined with [`::after`](https://github.com/iota-community/iota-wiki/blob/b020ce8428caf56625d6543d311672ec353d71d9/src/css/custom.css#L6) takes to much space and that's why together with `word-wrap: break-word;` it "breaks". So I think we need to restrict the size of the material icon. And is it intentional that the arrow icon doesn't show? Because if not we need to fix that too 😅 

Bildschirmfoto 2022-04-25 um 13 52 10

**Review by Dr-Electron — APPROVED** [review]

**Comment by huhn511** [comment]
Works well on Safari now!

**Review by huhn511 — APPROVED** [review]
LGMT 👍

**Pull request merged**
