### PR TITLE
Feat/new design

### PR DESCRIPTION
**Pull request by Dr-Electron**
# Description of change

This is the PR where we will implement the new design changes. It's still a draft and lots of things to do:

- [x] Fix social row (style, colours, alignment)
- [x] Change Fonts
- [x] Make cards prettier
- [x] Fix NavBar (I like the transparency, but maybe it should get opaque once you scroll?)
- [ ] Change bg and globe pictures to real SVGs :trollface:
- [x] Correct wiki wide background colors
- [x] Create the hero section on the landing page with the custom background
- [ ] Add search functionality
- [x] Change the mode toggle switch to the IOTA Blog switch style
- [x] Fix navbar hoover and active styling
- [x] Fix sidebar hoover and active styling
- [x] Discuss IOTA logo in footer copyright (it's in the design, but is this actually legal as it is community maintained?)
- [ ] Make scrollbar styling consistent across all sections
- [x] Discuss light theme with UX team

## Type of change

- Documentation Enhancment

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested the wiki locally and tested that all external links work

### CODE REVIEW

**Comment by jlvandenhout** [comment]
As long as we don't have a production deployment yet to get indexed by Algolia, I'd like to propose a client side search provider (like [this plugin](https://github.com/lelouch77/docusaurus-lunr-search)) for now so at least we have a somewhat functional searchbar.

**Comment by jlvandenhout** [comment]
I'm in the process of implementing the search UI from scratch as other solutions don't fit our needs (multiple search bars, local search, easy config). So I'll begin with the frontend so we can have a look at it, we can hook up any backend later to get it really working.

**Comment by jlvandenhout** [comment]
I think we've got the major styling done now, at least enough to get some feedback on our progress. I would like to merge this into dev to let others have a look at it using the live server. To this end I added a "Work in Progress" page as index page and temporarily moved the main page to a separate end point. I also set the `noIndex` option in the site config to prevent search engines indexing our pages as long as we are in development.

**Comment by Dr-Electron** [comment]
I will open some issues for the missing tasks and merge this for now

**Review by Phyloiota — APPROVED** [review]
okay i trust this person that i have never met and only know from the internet that all is perfect here :)

**Pull request merged**
