### PR TITLE
Implement mega menu component

### LINKED ISSUE #163: Replace dropdown lists with mega menus
The ground we are covering with the Wiki is vast and listing all kinds of different topics in standard dropdown menus to navigate them is starting to get confusing for readers.

To allow us to categorize and group these topics more clearly, we've opted for a mega menu component containing a grid like layout, instead of using linear dropdown lists.

The mega menu dropdown should probably have the following design features:

- The menu should be responsive just like standard dropdowns are currently. On desktop it will expand all categories and layout all items in a grid like layout. On mobile it will turn into a linear list of items with collapsing categories.
- The menu layout should consist of columns.
- Each column contains one or more items and/or categories.
- Each category contains multiple items.
- Items have a label and optionally a sublabel and/or an icon.
- The menu should be configurable from the Docusaurus configuration file.

### PR DESCRIPTION
**Pull request by jlvandenhout**
The Docusaurus classic theme allows navbar items to be configured. If a navbar item itself contains items, it is recognized and rendered as a dropdown component. This dropdown component gets the items list passed as property. These items have to be valid navbar items themselves, which forces us to misuse the DefaultNavbarItemSchema a little to get passed configuration validation, but other than that it allows us to pass arbitrary data to a custom dropdown component. Let's see how far we can get with this.

Closes #163

### CODE REVIEW

**Review by Dr-Electron — APPROVED** [review]

**Comment by slorber** [comment]
Hey

Not sure how to contact you but please add your site to our Docusaurus showcase!
https://docusaurus.io/showcase

It deserves an immediate "favorite" tag 🥇 

FYI we'll add custom navbar item types

**Comment by slorber** [comment]
I'd also be very interested to know more about your web page editor (I mean https://wiki.iota.org/edit/learn/about-iota/an-introduction-to-iota).

**Comment by Dr-Electron** [comment]
> I'd also be very interested to know more about your web page editor (I mean https://wiki.iota.org/edit/learn/about-iota/an-introduction-to-iota).

That's something for @jlvandenhout ;)
You can checkout his repo in the meantime:
https://github.com/jlvandenhout/docusaurus-plugin-docs-editor

**Comment by jlvandenhout** [comment]
> I'd also be very interested to know more about your web page editor (I mean https://wiki.iota.org/edit/learn/about-iota/an-introduction-to-iota).
> 
> 

Awesome for you to reach out! I also already had some great conversations about the idea of an editor on the Docusaurus Discord server. I did not find the time yet, but I'm really interested in taking the editor to a higher level to help the Docusaurus community. My Discord handle is jvdhout#4402.

**Pull request merged**
