### PR TITLE
Fix content carousel

### PR DESCRIPTION
**Pull request by jlvandenhout**
# Description of change

The content resolve logic relied on directory listing, which is not supported on GitHub pages. I reverted the logic back to the previous implementation, but kept the import relative to the `static` directory instead of `static/img`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested the wiki locally and tested that all external links work

### CODE REVIEW

**Review by Dr-Electron — APPROVED** [review]

**Comment by Dr-Electron** [comment]
Why the change from `static/img` to `static`?

**Comment by jlvandenhout** [comment]
> Why the change from `static/img` to `static`?

The `img` subfolder is arbitrary and I don't like hardcoding arbitrary paths, that's the only reason.

**Comment by Dr-Electron** [comment]
> > Why the change from `static/img` to `static`?
> 
> The `img` subfolder is arbitrary and I don't like hardcoding arbitrary paths, that's the only reason.

A yeah, you told me that 😅 Got it

**Review by Critical94 — APPROVED** [review]
LGTM

**Review by Critical94 — APPROVED** [review]

**Comment by Dr-Electron** [comment]
Rebased to main branch so we can test if it still works with the newest updates on main

**Comment by jlvandenhout** [comment]
Fixed

**Review by Dr-Electron — APPROVED** [review]

**Review by Critical94 — APPROVED** [review]

**Pull request merged**
