### PR TITLE
Add properties validation

### LINKED ISSUE #245: Add property type checks for components
Currently we do not utilize the React property system in our components, while I think we should. Using [property type checks](https://reactjs.org/docs/typechecking-with-proptypes.html) prevents components rendering incorrectly if the right properties are not passed and we can provide sane defaults.

### PR DESCRIPTION
**Pull request by jlvandenhout**
I've added property type checking and provided the defaults where defaults were used. This will help with #221 as ESLint will complain less.

Closes #245 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

### CODE REVIEW

**Review by lucas-tortora — APPROVED** [review]

**Comment by Critical94** [comment]
There are `Failed prop type:` warnings in the console on blog page

**Comment by jlvandenhout** [comment]
@Critical94 Ah thanks for letting me know, I'll fix those in a sec.

**Comment by Critical94** [comment]
Did something get mixed up here? There are many unrelated changes now :monocle_face:

**Comment by jlvandenhout** [comment]
> Did something get mixed up here? There are many unrelated changes now 🧐

Yes I screwed up, see Discord

**Comment by jlvandenhout** [comment]
@Critical94 Could you check again? I think I solved the mess.

**Review by Critical94 — APPROVED** [review]

**Pull request merged**
