### PR TITLE
Feat - Add developer resources to the navbar

### PR DESCRIPTION
**Pull request by lucas-tortora**
# Description of change

Added developer resources to navbar. As there isn't any content for a full blown section at the moment it's only a # link to the home page.

## Links to any relevant issues

fixes https://github.com/iota-community/iota-wiki/issues/642

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Wiki was built locally

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested the wiki locally and tested that all external links work

### CODE REVIEW

**Comment by lucas-tortora** [comment]
@Dr-Electron , @jlvandenhout could you take a look at this whenever you have a minute?

**Comment by lucas-tortora** [comment]
@Dr-Electron , @jlvandenhout could you take a look at this whenever you have a minute?

**Comment by Dr-Electron** [comment]
It's not like we didn't think about it yet.
But :trollface: 
layout

**Comment by lucas-tortora** [comment]
> It's not like we didn't think about it yet. But :trollface: layout Guess we need to look at that part of #642 first `We should make some room for tutorials, especially on smaller screens.`

I mean, I get the issue, but the same happens with Smart Contracts and About IOTA.It's actually a bit worse in those cases. I get that it's a layout issue, but it seems a bit out of scope for this PR.

**Comment by Dr-Electron** [comment]
That's why I would like to fix the nabber first before we "break" it with additional content 🤔 
I think this isn't out of scope for this PR imo.
But let's see what @jlvandenhout thinks. I don't want to decide alone

**Review by aleksei-korolev — APPROVED** [review]

**Comment by lucas-tortora** [comment]
> That's why I would like to fix the navbar first before we "break" it with additional content thinking I think this isn't out of scope for this PR imo. But let's see what @jlvandenhout thinks. I don't want to decide alone

It's a visual bug that's completely unrelated to the added code. A hard one to reproduce at that.  How can it be in scope?

**Comment by lucas-tortora** [comment]
> That's why I would like to fix the navbar first before we "break" it with additional content thinking I think this isn't out of scope for this PR imo. But let's see what @jlvandenhout thinks. I don't want to decide alone

It's a visual bug that's completely unrelated to the added code. A hard one to reproduce at that.  How can it be in scope?

**Comment by Dr-Electron** [comment]
You mean it happens without adding `Developer Resources` in the navbar?

**Comment by jlvandenhout** [comment]
Let's merge #698 and then merge this.

**Review by Dr-Electron — APPROVED** [review]

**Pull request merged**
